CREATE TABLE pessoa(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	ativo BOOLEAN NOT NULL,
	logradouro VARCHAR(255),
	numero VARCHAR(255),
	complemento VARCHAR(255),
	bairro VARCHAR(255),
	cep VARCHAR(255),
	cidade VARCHAR(255),
	estado VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
